### ISSUE TITLE
Button isn't pressed automatically

### ISSUE THREAD

**Issue by morfeyc** [omar07ibrahim/YouTube-Ad-Skipper#1]
Before, it's working great. I appreciate ur work.
But since yesterday, it seems that the "skip" button has stopped clicking automatically

**Comment by irvine48** [comment]
change this line in content,js

`let skipButton = document.getElementsByClassName("ytp-ad-skip-button ytp-button")[0];`

to

`let skipButton = document.getElementsByClassName("ytp-ad-skip-button-modern ytp-button")[0]`

**Comment by morfeyc** [comment]
It's worked, thx
